#!/usr/bin/env bash

# Author: Aine Fairbrother-Browne
# Date: 10/12/21

# requires a conda environment containing a plink installation
# run before script execution: conda activate plink 

# go to plink input dir - here are the pre-wrangled matrixeqtl files, with correct plink col names
cd /home/abrowne/projects/amppd_analysis/data/PLINK_input

# define name of file containing list of sample suffixes to use - generated by the get.file.lists.for.plink.metaanalysis() function
sample_file_path="./PP_PD_file_list_metaanalysis_plinkIN.txt"

# define location for output files 
out_file_path="/home/abrowne/projects/amppd_analysis/data/PLINK_output/"

# iterate over the sample suffixes in the sample file, run plink --meta-analysis on PD_suffix and PP_suffix pairs
while read file_suffix; 
do 
echo "Meta-analysing PP${file_suffix} and PD${file_suffix}"; 
outfile_prefix="${file_suffix%%_plinkIN.csv*}"
plink --meta-analysis "./PP${file_suffix}" "./PD${file_suffix}" --ci 0.95 --out "${out_file_path}PP_PD_meta${outfile_prefix}";
echo "Done";
done <${sample_file_path}



